name: DrinkBackend
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aioboto3=14.1.0
  - aiobotocore=2.21.1
  - aiofiles=24.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aioitertools=0.7.1
  - aiosignal=1.2.0
  - aiosmtplib=3.0.2
  - annotated-types=0.6.0
  - apscheduler=3.10.4
  - asttokens=3.0.0
  - attrs=24.3.0
  - blas=1.0
  - blinker=1.9.0
  - boto3=1.37.1
  - botocore=1.37.1
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cffi=1.17.1
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.11.12
  - cryptography=44.0.1
  - cudatoolkit=11.8.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - dnspython=2.4.2
  - email-validator=2.2.0
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - fastapi-mail=1.4.2
  - fmt=9.1.0
  - frozenlist=1.5.0
  - implicit=0.7.2
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=4.18.0
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libkrb5=1.21.3
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - lmdb=0.9.31
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multidict=6.1.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.5.0
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pydantic-core=2.33.2
  - pydantic-settings=2.6.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=307
  - pyzmq=26.4.0
  - readline=8.3
  - s3transfer=0.11.2
  - schedule=1.2.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=75.8.0
  - sniffio=1.3.1
  - spdlog=1.11.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.28
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - tzlocal=5.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asn1crypto==1.5.1
      - asyncpg==0.30.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.12.3
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - coverage==7.13.0
      - docopt==0.6.2
      - ecdsa==0.19.1
      - fastapi==0.115.4
      - greenlet==3.1.1
      - h11==0.14.0
      - idna==3.10
      - iniconfig==2.3.0
      - js2py==0.74
      - minio==7.2.15
      - packaging==24.1
      - passlib==1.7.4
      - pg8000==1.31.2
      - pipwin==0.5.2
      - pluggy==1.6.0
      - pyasn1==0.6.1
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==2.11.7
      - pyjsparser==2.7.1
      - pyjwt==2.9.0
      - pyprind==2.11.3
      - pysmartdl==1.3.4
      - pytest==9.0.2
      - pytest-asyncio==1.3.0
      - pytest-cov==7.0.0
      - python-dotenv==1.0.1
      - python-jose==3.5.0
      - python-multipart==0.0.20
      - requests==2.32.3
      - rsa==4.9.1
      - scikit-surprise==1.1.4
      - scramp==1.4.5
      - six==1.16.0
      - soupsieve==2.6
      - sqlalchemy==2.0.36
      - starlette==0.41.2
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvicorn==0.32.0
prefix: /home/nikunj/miniconda/envs/DrinkBackend
